# Generated by Django 5.2.8 on 2025-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_facebook_link_profile_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, help_text='Image outlining the service', null=True, upload_to='services/'),
        ),
    ]
